#!/usr/bin/env ruby

require 'fileutils'
require 'erb'
require_relative 'lib/nginx_config'

TEMPLATE               = File.join(File.dirname(__FILE__), 'templates/nginx.conf.erb')
USER_CONFIG            = 'static.json'
NGINX_CONFIG           = 'config/nginx.conf'

context = NginxConfig.new(USER_CONFIG).context
erb = ERB.new(File.read(TEMPLATE)).result(context)
File.write(NGINX_CONFIG, erb)
